name: pull request

on:
  pull_request:
    branches: [master]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.14'

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

    - name: Install
      run: |
        echo 'Installing packages...'
        npm install
        
    - name: Frontend lint
      run: |
        echo 'Checking Linting in Frontend'
        cd frontend
        npm run lint
